# Generated by Django 5.1.4 on 2026-07-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], default='First Semester', max_length=30),
        ),
    ]
