# Generated by Django 5.1.4 on 2026-07-24 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0003_practiceexam_examattempt_practicequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='exam_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattemptanswer',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattemptanswer',
            name='correct_choice_key',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='examattemptanswer',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examattemptanswer',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examattemptanswer',
            name='selected_choice_key',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examattemptanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ScholarHub.practicequestion'),
        ),
    ]
