# Generated by Django 6.0.7 on 2026-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0004_examattempt_exam_data_examattemptanswer_choices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
