# Generated by Django 6.0.7 on 2026-07-29 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0005_alter_course_options_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattemptanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='examattemptanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='examattemptanswer',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='practicechoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='practiceexam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='practiceexam',
            name='department',
        ),
        migrations.RemoveField(
            model_name='practiceexam',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='practicequestion',
            name='exam',
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Optional quiz timer in minutes.', null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=20)),
                ('semester', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=30)),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ScholarHub.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ScholarHub.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ScholarHub.faculty')),
            ],
            options={
                'ordering': ('course__code', 'text'),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('time_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='ScholarHub.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='ScholarHub.studentprofile')),
            ],
            options={
                'ordering': ('-date_completed',),
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=1)),
                ('correct_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='ScholarHub.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='ScholarHub.quizattempt')),
            ],
            options={
                'ordering': ('question__text',),
            },
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
        migrations.DeleteModel(
            name='ExamAttemptAnswer',
        ),
        migrations.DeleteModel(
            name='PracticeChoice',
        ),
        migrations.DeleteModel(
            name='PracticeExam',
        ),
        migrations.DeleteModel(
            name='PracticeQuestion',
        ),
    ]
