# Generated by Django 6.0.7 on 2026-07-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0006_remove_examattemptanswer_attempt_and_more'),
        ('ScholarHub', '0006_remove_textbook_cover_image_remove_textbook_pdf_textbook_content_and_more'),
    ]

    operations = [
    ]
