# Generated by Django 6.0.7 on 2026-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0007_merged_textbook_quiz_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_backgrounds/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.AlterField(
            model_name='textbook',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full note content typed from the admin panel.'),
        ),
    ]
