# Generated by Django 6.0.7 on 2026-08-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0008_landingbackground_alter_textbook_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPanelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_panels/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
