# Generated by Django 6.0.7 on 2026-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarHub', '0009_landingpanelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='textbooks/covers/'),
        ),
    ]
